### ISSUE TITLE
Replicator and Seals not working?

### ISSUE THREAD

**Issue by ryukra** [nekosune/Thaumic_Exploration#22] opened 2015-03-05 23:09 UTC
I noticed that the seals and the replicator are not working. 
Using the latest build ThaumicExploration-1.7.10-1.1-37.jar

**Comment by reiniken** [comment] 2015-03-24 21:48
Same boat

**Comment by renadi** [comment] 2015-03-24 22:24
Seals don't work, specifically in MP at least

**Comment by Qohelethh** [comment] 2015-04-09 15:27
Seals don't work in SMP. Any chance this will get fixed?

**Comment by smbarbour** [comment] 2015-05-09 00:49
Duplicate of #11

**Comment by Unrepentant-Atheist** [comment] 2015-06-01 07:42
Where can I download the furthest fork compiled for 1.7.10?

**Closed** 2015-06-17 13:57 UTC
